name: Check pull request

on:
  pull_request:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
  lint:
    name: Lint
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Python Setup"
        uses: actions/setup-python@v5
      - name: "Install dependencies"
        run: pip install -r requirements.txt
      - name: "Lint"
        run: bash scripts/lint.sh
  testing:
    name: Testing
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Python Setup"
        uses: actions/setup-python@v5
      - name: "Install dependencies"
        run: pip install -r requirements.txt
      - name: "Lint"
        run: bash scripts/test.sh
